version: "3.8"
services:
    php:
        build: .
        container_name: onboarding-block5-challenge
        working_dir: /var/www/
        volumes:
            - ./:/var/www
networks:
    php:
        driver: bridge
